### PR TITLE
fix: make use-query working with Refs

### PR DESCRIPTION
**Pull request by aantipov**
Documentation says that I need to wrap keys into `reactive` and pass an object of refs  https://vue-query.vercel.app/#/guides/query-keys
image

To me, as a developer, this way of passing keys seems very unnatural and unintuitive (not to say, complicated) 
In ReactQuery I used to pass just an array of primitive values, like `useQuery(['book', bookId], ....)`. 
I want to have a similar Developer experience.

This fix makes it possible to pass an array of Refs.

I also added a test which ensures it is working

### CODE REVIEW

**Comment by DamianOsipiuk** [comment]
Hi @aantipov,
Would you mind also changing the documentation to reflect the current change?

**Comment by henribru** [comment]
This is a pretty nice quality-of-life improvement. One edge case though: Since `unref` only shallowly unwraps refs, any refs nested further down still need to be wrapped in an object. It might be worth pointing out in the docs that this only works with refs in the top-level of the query key array,

**Comment by aantipov** [comment]
@henribru 
>any refs nested further down still need to be wrapped in an object.

you mean this kind of use case 
```js
const preview = ref(true);
useQuery(['todo', { preview  }], ...)
```
?

This use case is probably working fine already without a need of any extra action.
The only thing that might go wrong in this use case is proper serialization by ReactQuery. Not sure about that.

What I aimed to do next is to make the whole keys array reactive under the hood. By doing so, all the inner refs will get unwrapped and we ensure proper serialisation by ReactQuery. And developers don't need to bother.

I'm going to create a PR for this soon

**Comment by henribru** [comment]
I meant either something like `['todo', [[ preview ]]` (which I don't think would work?) or `['todo', { preview: [ preview ] }]` (not really sure if this would work?). Not the most realistic examples, but in general nesting arrays inside other arrays or objects inside the query keys might have its use.

But if you're planning on implementing proper recursive unrefing then that should take care of these issues. That sounds like an awesome change, looking forward to it!

**Pull request merged**
