### PR TITLE
docs: fix nuxt 3 usage

### PR DESCRIPTION
**Pull request by sondh0127**
Nuxt 3 uses useState API to sync state between server and client

### CODE REVIEW

**Comment by DamianOsipiuk** [comment]
@sondh0127 Unfortunately this does not work as expected.
It sends the rendered page from the server, but `queryClient` is not preserved in the payload.
Tried your solution as well as fiddling with `context.ssrContext.payload`.

When i hook earlier, like `app:created` then `queryClient` state is properly applied to the payload, but at that point it does not contain and query data, so it goes to the client empty, which is not helpfull.

It was working before so `nuxt` actually broke something.

I would suggest filing a ticket in the nuxt repo or waiting for rc.7 to check if it improves the situation.

**Comment by DamianOsipiuk** [comment]
When you look at the source of the page, at the bottom there is a Javascript object attached, which should contain the cache content at a given key.
The problem is not that the variable is empty, but that the variable is actually not transfered to the client.

This means that on the client your query will refetch, which is unwanted in some cases.

**Comment by sondh0127** [comment]
> 
Pic 1: I also saw the data with vue-query key in source file
image
Pic 2: There is not refresh request at client
image

**Comment by DamianOsipiuk** [comment]
Which version of `nuxt` are you using?

**Comment by sondh0127** [comment]
I'm use this one on the reproduction.
```
  "devDependencies": {
    "nuxt": "3.0.0-rc.6"
  },
  "dependencies": {
    "vue-query": "^2.0.0-beta.5"
  }
```

**Comment by DamianOsipiuk** [comment]
Hmm, interesting. I would have to double check, cause it did not work for me for some reason.

**Comment by genu** [comment]
I'm not sure if its related, but in my nuxt setup, I'm unable to import `hydrate` and `dehydrate`:

CleanShot 2022-08-13 at 13 18 52@2x

**Pull request merged**
